#!/bin/bash

#tor-daemon2.sh
#Developer Leandro Santos - https://github.com/leandroibov

echo "Tor-Daemon2";
echo "";

echo "Creating Tor Instance 2 -> 127.0.0.1 and port 9060";
echo "Instância 2 do tor service rodará em 127.0.0.1 e porta 9060";
sudo cat > /etc/tor/torrc.2 << EOF
SocksPort 9060
ControlPort 9061
DataDirectory /var/lib/tor2
EOF

echo;
echo "Configured torrc.2 file:";
echo "Configurando arquivo torrc.2";
cat /etc/tor/torrc.2;
echo;
ls /etc/tor/;
echo;
echo "Acionando Instância 2 do Tor";
echo "Triggering Tor Instance 2"
echo "sudo tor -f /etc/tor/torrc.2";
echo;
echo "ATENÇÃO: PARA DESLIGAR O TOR-DAEMON2, USE CONTROL + C!";
echo "WARNING: TO TURN OFF TOR-DAEMON2, USE CONTROL + C!";
echo "sudo tor -f /etc/tor/torrc.2;";
echo;
sudo tor -f /etc/tor/torrc.2;
echo;
