#!/bin/bash

#tor-daemon2-bridger.sh
#Developer Leandro Santos - https://github.com/leandroibov

echo "Tor-Daemon2-Bridger";
echo "Precisa ter instalado o obfs4proxy - Links abaixo:";
echo "https://packages.debian.org/buster/amd64/obfs4proxy/download";
echo "https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird";
echo "sudo apt-get install obfs4proxy";
echo "";
echo "Bridges devem ser copiadas inteiras para o arquivo torrc como são fornecidas com suas fingerprints e outros dados";
echo "Exemplo1: obfs4 89.10.110.191:7624 7EC3CE9AB0640524C77FCF361C85E50A9E07F506 cert=i9s53eikMKz4BiU/yYyFpJaBfGm/9xvNf97dnkI6iPg3Ls5TRoyOwhaIQprLgPruBf/zYA iat-mode=2";
echo;
echo "Colete bridges do tipo obfs4 em https://bridges.torproject.org/bridges";
echo "--------------------------------------------------------------";
read -rp "Digite a Bridge obfs4 que deseja cadastrar no torrc.2:" bridge
echo "--------------------------------------------------------------";
echo "A bridge escolhida foi: $bridge"
echo "--------------------------------------------------------------";
echo "";

echo;

echo "Creating Tor Instance 2 com bridges -> 127.0.0.1 and port 9060";
echo "Instância 2 do tor service rodará com bridge em 127.0.0.1 e porta 9060";
sudo cat > /etc/tor/torrc.2 << EOF
SocksPort 9060
ControlPort 9061
DataDirectory /var/lib/tor2

UseBridges 1
ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy managed
Bridge "$bridge"
EOF

echo;
echo "Configured torrc.2 file:";
echo "Configurando arquivo torrc.2";
cat /etc/tor/torrc.2;
echo;
ls /etc/tor/;
echo;
echo "Acionando Instância 2 do Tor com Bridge";
echo "Triggering Tor Instance 2 with Bridge"
echo "sudo tor -f /etc/tor/torrc.2";
echo;
echo "ATENÇÃO: PARA DESLIGAR O TOR-DAEMON2, USE CONTROL + C!";
echo "WARNING: TO TURN OFF TOR-DAEMON2, USE CONTROL + C!";
echo "sudo tor -f /etc/tor/torrc.2;";
echo;
sudo tor -f /etc/tor/torrc.2;
echo;
